name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-readme:
    name: Update Waka Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: 'en'
          SHOW_LOC_CHART: 'False'
          SHOW_TOTAL_CODE_TIME: 'False'
          SHOW_PROFILE_VIEWS: 'False'
          SHOW_LINES_OF_CODE: 'False'
          SHOW_PROJECTS: 'False'
